import os
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np

print("Generating transaction dataset...")
np.random.seed(42)
num_samples = 10000

X = np.zeros((num_samples, 3), dtype=np.float32)
y = np.zeros((num_samples, 1), dtype=np.float32)

for i in range(num_samples):
    r = np.random.rand()
    if r > 0.85:
        X[i][0] = np.random.uniform(0.5, 1.0)
        X[i][1] = np.random.uniform(2.0, 4.0)
        X[i][2] = 1.0
        y[i][0] = 1.0
    elif r > 0.75:
        X[i][0] = np.random.uniform(0.5, 1.0)
        X[i][1] = np.random.uniform(2.0, 4.0)
        X[i][2] = 0.0
        y[i][0] = 0.0
    else:
        X[i][0] = np.random.uniform(0.01, 0.4)
        X[i][1] = np.random.uniform(6.0, 22.0)
        X[i][2] = 0.0
        y[i][0] = 0.0
X_tensor = torch.tensor(X)
y_tensor = torch.tensor(y)


class EnPassantNet(nn.Module):
    def __init__(self):
        super(EnPassantNet, self).__init__()
        self.layer1 = nn.Linear(3, 8)
        self.relu = nn.ReLU()
        self.layer2 = nn.Linear(8, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        x = self.layer1(x)
        x = self.relu(x)
        x = self.layer2(x)
        x = self.sigmoid(x)
        return x


model = EnPassantNet()
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)

print("Training AI Core...")
for epoch in range(500):
    optimizer.zero_grad()
    outputs = model(X_tensor)
    loss = criterion(outputs, y_tensor)
    loss.backward()
    optimizer.step()

current_dir = os.path.dirname(os.path.abspath(__file__))
export_path = os.path.join(current_dir, "..", "engine", "weights.h")

print(f"Exporting tensors to {export_path}...")
w1 = model.layer1.weight.detach().numpy()
b1 = model.layer1.bias.detach().numpy()
w2 = model.layer2.weight.detach().numpy()
b2 = model.layer2.bias.detach().numpy()

with open(export_path, "w") as f:
    f.write("// EN_PASSANT AI WEIGHTS (AUTOGENERATED)\n")
    f.write("#pragma once\n\n")

    f.write("const float W1[8][3] = {\n")
    for row in w1:
        f.write("    {" + ", ".join(f"{val:.6f}" for val in row) + "},\n")
    f.write("};\n\n")

    f.write("const float B1[8] = {" + ", ".join(f"{val:.6f}" for val in b1) + "};\n\n")

    f.write("const float W2[1][8] = {\n")
    for row in w2:
        f.write("    {" + ", ".join(f"{val:.6f}" for val in row) + "},\n")
    f.write("};\n\n")

    f.write("const float B2[1] = {" + ", ".join(f"{val:.6f}" for val in b2) + "};\n")

print("PyTorch tensors converted to native C++.")
